"""URL configuration for the QuickScale billing module."""

from django.urls import path

from quickscale_modules_billing.views import (
    BillingDashboardView,
    BillingPortalReturnView,
    CancelSubscriptionView,
    CreditBalanceView,
    CreditTransactionListView,
    CreateBillingPortalSessionView,
    CreateCheckoutSessionView,
    CreateSubscriptionCheckoutView,
    OrgPricingPageView,
    PlanListView,
    PricingPageView,
    PurchaseCancelView,
    PurchaseSuccessView,
    StripePublishableKeyView,
    StripeWebhookView,
    SubscriptionCancelView,
    SubscriptionDetailView,
    SubscriptionSuccessView,
)

DASHBOARD_PATH = "billing/dashboard/"
PURCHASE_SUCCESS_PATH = "billing/purchase/success/"
PURCHASE_CANCEL_PATH = "billing/purchase/cancel/"
PORTAL_RETURN_PATH = "billing/portal/return/"
PRICING_PATH = "billing/pricing/"
SUBSCRIPTION_SUCCESS_PATH = "billing/subscription/success/"
SUBSCRIPTION_CANCEL_PATH = "billing/subscription/cancel/"

app_name = "quickscale_billing"

urlpatterns = [
    path(
        "orgs/<slug:org_slug>/api/billing/config/",
        StripePublishableKeyView.as_view(),
        name="org-billing-config",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/plans/",
        PlanListView.as_view(),
        name="org-subscription-plans",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/balance/",
        CreditBalanceView.as_view(),
        name="org-credit-balance",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/transactions/",
        CreditTransactionListView.as_view(),
        name="org-credit-transactions",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/purchase/checkout/",
        CreateCheckoutSessionView.as_view(),
        name="org-purchase-checkout",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/subscription/",
        SubscriptionDetailView.as_view(),
        name="org-subscription-detail",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/subscription/checkout/",
        CreateSubscriptionCheckoutView.as_view(),
        name="org-subscription-checkout",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/subscription/cancel/",
        CancelSubscriptionView.as_view(),
        name="org-subscription-cancel-current",
    ),
    path(
        "orgs/<slug:org_slug>/api/billing/portal/",
        CreateBillingPortalSessionView.as_view(),
        name="org-billing-portal-session",
    ),
    path(
        "orgs/<slug:org_slug>/billing/dashboard/",
        BillingDashboardView.as_view(),
        name="org-billing-dashboard",
    ),
    path(
        "orgs/<slug:org_slug>/billing/portal/return/",
        BillingPortalReturnView.as_view(),
        name="org-portal-return",
    ),
    path(
        "orgs/<slug:org_slug>/billing/pricing/",
        OrgPricingPageView.as_view(),
        name="org-pricing-page",
    ),
    path(
        "orgs/<slug:org_slug>/billing/purchase/success/",
        PurchaseSuccessView.as_view(),
        name="org-purchase-success",
    ),
    path(
        "orgs/<slug:org_slug>/billing/purchase/cancel/",
        PurchaseCancelView.as_view(),
        name="org-purchase-cancel",
    ),
    path(
        "orgs/<slug:org_slug>/billing/subscription/success/",
        SubscriptionSuccessView.as_view(),
        name="org-subscription-success",
    ),
    path(
        "orgs/<slug:org_slug>/billing/subscription/cancel/",
        SubscriptionCancelView.as_view(),
        name="org-subscription-cancel",
    ),
    path(
        "api/billing/config/",
        StripePublishableKeyView.as_view(),
        name="billing-config",
    ),
    path(
        "api/billing/plans/",
        PlanListView.as_view(),
        name="subscription-plans",
    ),
    path(
        "api/billing/balance/",
        CreditBalanceView.as_view(),
        name="credit-balance",
    ),
    path(
        "api/billing/transactions/",
        CreditTransactionListView.as_view(),
        name="credit-transactions",
    ),
    path(
        "api/billing/purchase/checkout/",
        CreateCheckoutSessionView.as_view(),
        name="purchase-checkout",
    ),
    path(
        "api/billing/subscription/",
        SubscriptionDetailView.as_view(),
        name="subscription-detail",
    ),
    path(
        "api/billing/subscription/checkout/",
        CreateSubscriptionCheckoutView.as_view(),
        name="subscription-checkout",
    ),
    path(
        "api/billing/subscription/cancel/",
        CancelSubscriptionView.as_view(),
        name="subscription-cancel-current",
    ),
    path(
        "api/billing/portal/",
        CreateBillingPortalSessionView.as_view(),
        name="billing-portal-session",
    ),
    path(
        DASHBOARD_PATH,
        BillingDashboardView.as_view(),
        name="billing-dashboard",
    ),
    path(
        PORTAL_RETURN_PATH,
        BillingPortalReturnView.as_view(),
        name="portal-return",
    ),
    path(
        PRICING_PATH,
        PricingPageView.as_view(),
        name="pricing-page",
    ),
    path(
        PURCHASE_SUCCESS_PATH,
        PurchaseSuccessView.as_view(),
        name="purchase-success",
    ),
    path(
        PURCHASE_CANCEL_PATH,
        PurchaseCancelView.as_view(),
        name="purchase-cancel",
    ),
    path(
        SUBSCRIPTION_SUCCESS_PATH,
        SubscriptionSuccessView.as_view(),
        name="subscription-success",
    ),
    path(
        SUBSCRIPTION_CANCEL_PATH,
        SubscriptionCancelView.as_view(),
        name="subscription-cancel",
    ),
    path(
        "billing/webhooks/stripe/",
        StripeWebhookView.as_view(),
        name="stripe-webhook",
    ),
]
