# Generated by Django 6.0.6 on 2026-06-30 18:16

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickscale_modules_crm", "0010_refresh_rls_policies_nullif_guard"),
        ("quickscale_modules_orgs", "0004_organizationtombstone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name"],
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactnote",
            options={"base_manager_name": "all_objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="deal",
            options={"base_manager_name": "all_objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dealnote",
            options={"base_manager_name": "all_objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={"base_manager_name": "all_objects", "ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"base_manager_name": "all_objects", "ordering": ["name"]},
        ),
        migrations.AlterModelManagers(
            name="company",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="contactnote",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="deal",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dealnote",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stage",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tag",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="company",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contactnote",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="dealnote",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="quickscale_modules_orgs.organization",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="contact",
                    constraint=models.UniqueConstraint(
                        fields=("id", "organization"), name="crm_contact_id_org_unique"
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="deal",
                    constraint=models.UniqueConstraint(
                        fields=("id", "organization"), name="crm_deal_id_org_unique"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
