"""Deterministic module wiring renderer.

Managed wiring files are generated from structured module specs rather than
string patching `settings/base.py` and `urls.py`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any, Iterable, Mapping


@dataclass(frozen=True)
class ModuleWiringSpec:
    """Structured wiring for a single module."""

    apps: tuple[str, ...] = ()
    middleware: tuple[str, ...] = ()
    settings: Mapping[str, Any] = field(default_factory=dict)
    url_includes: tuple[tuple[str, str], ...] = ()


def _merge_unique(items: list[str], additions: Iterable[str]) -> None:
    """Append additions to items while preserving first-seen order."""
    seen = set(items)
    for value in additions:
        if value not in seen:
            items.append(value)
            seen.add(value)


def _sort_module_items(
    module_specs: Mapping[str, ModuleWiringSpec],
) -> list[tuple[str, ModuleWiringSpec]]:
    """Sort module specs by module name for deterministic output."""
    return sorted(module_specs.items(), key=lambda item: item[0])


def collect_wiring(
    module_specs: Mapping[str, ModuleWiringSpec],
) -> tuple[list[str], list[str], dict[str, Any], list[tuple[str, str]]]:
    """Collect merged wiring artifacts from module specs."""
    apps: list[str] = []
    middleware: list[str] = []
    settings: dict[str, Any] = {}
    urls: list[tuple[str, str]] = []

    for _, spec in _sort_module_items(module_specs):
        _merge_unique(apps, spec.apps)
        _merge_unique(middleware, spec.middleware)

        # Last writer wins for setting collisions, deterministic by module name.
        for key, value in spec.settings.items():
            settings[key] = value

        for route, include_target in spec.url_includes:
            include_tuple = (route, include_target)
            if include_tuple not in urls:
                urls.append(include_tuple)

    return apps, middleware, settings, urls


def render_settings_modules_py(module_specs: Mapping[str, ModuleWiringSpec]) -> str:
    """Render `<package>/settings/modules.py` content."""
    apps, middleware, settings, _ = collect_wiring(module_specs)

    apps_text = pformat(apps, sort_dicts=True, width=88)
    middleware_text = pformat(middleware, sort_dicts=True, width=88)
    settings_text = pformat(settings, sort_dicts=True, width=88)

    return (
        '"""QuickScale managed module settings wiring.\n\n'
        "DO NOT EDIT MANUALLY. This file is regenerated by QuickScale.\n"
        '"""\n\n'
        f"MODULE_INSTALLED_APPS: list[str] = {apps_text}\n\n"
        f"MODULE_MIDDLEWARE: list[str] = {middleware_text}\n\n"
        f"MODULE_SETTINGS: dict[str, object] = {settings_text}\n"
    )


def render_urls_modules_py(module_specs: Mapping[str, ModuleWiringSpec]) -> str:
    """Render `<package>/urls_modules.py` content."""
    _, _, _, urls = collect_wiring(module_specs)

    header = (
        '"""QuickScale managed module URL wiring.\n\n'
        "DO NOT EDIT MANUALLY. This file is regenerated by QuickScale.\n"
        '"""\n\n'
    )

    if urls:
        pattern_lines = [
            f'    path("{route}", include("{include_target}")),'
            for route, include_target in urls
        ]
        patterns_body = "\n".join(pattern_lines)
        return (
            header
            + "from django.urls import include, path\n\n"
            + "MODULE_URLPATTERNS = [\n"
            + f"{patterns_body}\n"
            + "]\n"
        )
    else:
        return (
            header
            + "from django.urls import URLPattern\n\n"
            + "MODULE_URLPATTERNS: list[URLPattern] = []\n"
        )


def write_managed_wiring(
    package_dir: Path,
    module_specs: Mapping[str, ModuleWiringSpec],
) -> None:
    """Write managed wiring files into a generated project package."""
    settings_dir = package_dir / "settings"
    settings_dir.mkdir(parents=True, exist_ok=True)

    settings_modules_path = settings_dir / "modules.py"
    urls_modules_path = package_dir / "urls_modules.py"

    settings_modules_path.write_text(render_settings_modules_py(module_specs))
    urls_modules_path.write_text(render_urls_modules_py(module_specs))
