"""QuickScale managed module settings wiring.

DO NOT EDIT MANUALLY. This file is regenerated by QuickScale.
"""

MODULE_INSTALLED_APPS: list[str] = []
MODULE_MIDDLEWARE: list[str] = []
MODULE_SETTINGS: dict[str, object] = {}
