[tool.poetry]
name = "quickscale-cli"
version = "0.64.0"
description = "Command-line interface for QuickScale Django project generator"
authors = ["Experto AI <victor@experto.ai>"]
license = "Apache-2.0"
keywords = ["django", "cli", "project-generator", "saas"]
homepage = "https://github.com/Experto-AI/quickscale"
repository = "https://github.com/Experto-AI/quickscale"
documentation = "https://github.com/Experto-AI/quickscale/tree/main/docs"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
]
packages = [{include = "quickscale_cli", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.3.0"
quickscale-core = {path = "../quickscale_core"}

[tool.poetry.group.dev.dependencies]
# Dev dependencies centralized in root pyproject.toml
# Use: poetry install from repository root

[tool.poetry.scripts]
quickscale = "quickscale_cli.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=quickscale_cli",
    "--cov-report=term-missing",
    "--cov-report=html",
    "-m", "not e2e",  # Skip E2E tests by default (run with: pytest -m e2e)
]

# Ruff and mypy configurations centralized in root ruff.toml and mypy.ini
# Package-specific isort override
[tool.ruff.lint.isort]
known-first-party = ["quickscale_cli", "quickscale_core"]

# Package-specific mypy overrides
[[tool.mypy.overrides]]
module = "quickscale_core.*"
ignore_missing_imports = true
