# Generated by Django 6.0.6 on 2026-06-30 18:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quickscale_modules_blog", "0003_refresh_rls_policies_nullif_guard"),
        ("quickscale_modules_orgs", "0004_organizationtombstone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogmediaasset",
            options={"base_manager_name": "all_objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"base_manager_name": "all_objects", "ordering": ["name"]},
        ),
        migrations.AlterModelManagers(
            name="blogmediaasset",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tag",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
