#!/usr/bin/env bash
set -euo pipefail

# Unified version tool: check, sync, embed, apply
# Usage:
#   scripts/version_tool.sh check
#   scripts/version_tool.sh sync [--apply]
#   scripts/version_tool.sh embed
#   scripts/version_tool.sh apply

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="$ROOT/VERSION"

PYPROJECTS=("$ROOT/quickscale_core/pyproject.toml" "$ROOT/quickscale_cli/pyproject.toml" "$ROOT/quickscale/pyproject.toml")
PACKAGES=("$ROOT/quickscale_core/src/quickscale_core" "$ROOT/quickscale_cli/src/quickscale_cli")

read_version() {
  if [[ -f "$VERSION_FILE" ]]; then
    cat "$VERSION_FILE" | tr -d '\r' | sed -e 's/^\s*//' -e 's/\s*$//'
  else
    echo ""
  fi
}

get_pyproject_version() {
  local path="$1"
  if [[ -f "$path" ]]; then
    grep -m1 '^version' "$path" | sed -E 's/.*"([^"]+)".*/\1/' || true
  fi
}

update_pyproject() {
  local path="$1"; local version="$2"
  if [[ ! -f "$path" ]]; then
    echo "  (missing) $path"
    return 1
  fi
  local before; before=$(cat "$path")
  # Replace the first version = "..." occurrence (full match including old version)
  sed -E -i "0,/^version[[:space:]]*=[[:space:]]*\"[^\"]+\"/s//version = \"${version}\"/" "$path"
  local after; after=$(cat "$path")
  if [[ "$before" != "$after" ]]; then
    echo "  UPDATED: $path"
    return 0
  else
    echo "  NO-CHANGE: $path"
    return 2
  fi
}

find_yaml_docs() {
  local out=()
  if [[ -d "$ROOT/docs" ]]; then
    while IFS= read -r -d $'\0' f; do
      # check for version: field in the file
      if grep -Eq '^\s*version\s*:' "$f"; then
        out+=("$f")
      fi
    done < <(find "$ROOT/docs" -type f \( -name '*.md' -o -name '*.yml' -o -name '*.yaml' \) -print0)
  fi
  printf '%s\n' "${out[@]:-}"
}

update_yaml_versions() {
  local version="$1"
  shift
  local updated=()
  for p in "$@"; do
    local before; before=$(cat "$p")
    sed -E -i "s|^(\s*version\s*:\s*).*|\1${version}|" "$p"
    local after; after=$(cat "$p")
    if [[ "$before" != "$after" ]]; then
      updated+=("$p")
      echo "  Updated YAML: $p"
    fi
  done
  return 0
}

embed_version_into_packages() {
  local version="$1"
  for pkg in "${PACKAGES[@]}"; do
    if [[ -d "$pkg" ]]; then
      local target="$pkg/_version.py"
      printf '%s\n' "# Auto-generated by scripts/version_tool.sh" "__version__ = \"${version}\"" > "$target"
      echo "Wrote $target"
    else
      echo "Package dir not found, skipping: $pkg"
    fi
  done
}

cmd_check() {
  local version; version=$(read_version)
  echo "Repository VERSION: ${version}"
  local ok=0
  for p in "${PYPROJECTS[@]}"; do
    if [[ -f "$p" ]]; then
      local pv; pv=$(get_pyproject_version "$p")
      echo "$p: pyproject version = ${pv}"
      if [[ "${pv}" != "${version}" ]]; then
        echo "  MISMATCH: ${p} != VERSION"
        ok=2
      fi
    else
      echo "$p: (missing)"
    fi
  done
  # local docs; docs=( $(find_yaml_docs) )
  # if [[ ${#docs[@]} -gt 0 ]]; then
  #   echo "Found ${#docs[@]} docs with version fields (sample):"
  #   for i in "${docs[@]:0:10}"; do echo " - $i"; done
  # else
  #   echo "No docs with version fields found"
  # fi
  return $ok
}

cmd_sync() {
  local apply=false
  if [[ "${1:-}" == "--apply" ]]; then apply=true; fi
  local version; version=$(read_version)
  echo "Repository VERSION: ${version}"
  local any=false
  for p in "${PYPROJECTS[@]}"; do
    if [[ "$apply" == true ]]; then
      update_pyproject "$p" "$version" || true
    else
      echo "$p: will-update (dry-run) if version differs"
    fi
  done

  mapfile -t yamls < <(find_yaml_docs)
  if [[ ${#yamls[@]} -gt 0 ]]; then
    if [[ "$apply" == true ]]; then
      update_yaml_versions "$version" "${yamls[@]}"
    else
      echo "Found ${#yamls[@]} docs with version fields (dry-run):"
      for p in "${yamls[@]}"; do echo " - $p"; done
    fi
  else
    echo "No docs with version fields found"
  fi
  return 0
}

cmd_embed() {
  local version; version=$(read_version)
  embed_version_into_packages "$version"
}

usage() {
  cat <<EOF
Usage: $0 <command> [--apply]

Commands:
  check           Verify VERSION matches pyproject.toml versions and list docs
  sync [--apply]  Sync pyproject.toml/docs from VERSION (dry-run unless --apply)
  embed           Embed VERSION into package-level _version.py files
  apply           Run sync --apply then embed

Examples:
  $0 check
  $0 sync --apply
  $0 embed
  $0 apply

After adding this file make it executable: chmod +x $0
EOF
}

main() {
  if [[ $# -lt 1 ]]; then usage; exit 2; fi
  cmd="$1"; shift
  case "$cmd" in
    check)
      cmd_check || exit $? ;;
    sync)
      cmd_sync "$@" || exit $? ;;
    embed)
      cmd_embed || exit $? ;;
    apply)
      cmd_sync --apply || exit $? ;
      cmd_embed || exit $? ;;
    -h|--help|help)
      usage ;;
    *)
      echo "Unknown command: $cmd"; usage; exit 2 ;;
  esac
}

main "$@"
