# Generated by Django 6.0.3 on 2026-03-26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="default",
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Backup artifacts older than this many days are pruned.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "naming_prefix",
                    models.CharField(
                        default="db",
                        help_text="Prefix used when generating backup artifact filenames.",
                        max_length=64,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        choices=[
                            ("local", "Local private storage"),
                            ("private_remote", "Private remote offload"),
                        ],
                        default="local",
                        help_text="Backups remain private regardless of target mode.",
                        max_length=20,
                    ),
                ),
                (
                    "local_directory",
                    models.CharField(
                        default=".quickscale/backups",
                        help_text="Private local directory for stored backup artifacts.",
                        max_length=255,
                    ),
                ),
                ("remote_bucket_name", models.CharField(blank=True, max_length=255)),
                (
                    "remote_prefix",
                    models.CharField(
                        blank=True, default="backups/private", max_length=255
                    ),
                ),
                ("remote_endpoint_url", models.CharField(blank=True, max_length=255)),
                ("remote_region_name", models.CharField(blank=True, max_length=64)),
                (
                    "remote_access_key_id_env_var",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "remote_secret_access_key_env_var",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "automation_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Metadata only. Scheduled execution remains command-driven.",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        default="0 2 * * *",
                        help_text="Cron-like schedule documentation for external schedulers.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Backup policy",
                "verbose_name_plural": "Backup policies",
                "db_table": "quickscale_modules_backups_policy",
            },
        ),
        migrations.CreateModel(
            name="BackupArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                (
                    "storage_target",
                    models.CharField(
                        choices=[
                            ("local", "Local private storage"),
                            ("private_remote", "Private remote offload"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("local_path", models.CharField(blank=True, max_length=512)),
                ("remote_key", models.CharField(blank=True, max_length=512)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("backup_format", models.CharField(default="json", max_length=32)),
                ("database_engine", models.CharField(max_length=255)),
                ("database_name", models.CharField(blank=True, max_length=255)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("validated", "Validated"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                            ("restored", "Restored"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("trigger", models.CharField(default="manual", max_length=32)),
                ("validation_notes", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quickscale_backup_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup artifact",
                "verbose_name_plural": "Backup artifacts",
                "db_table": "quickscale_modules_backups_artifact",
                "ordering": ["-created_at"],
            },
        ),
    ]
